### ISSUE TITLE
get_priors(): error for binomial models (issue with new rstanarm?) 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#212] opened 2020-07-21 09:31 UTC
``` r
library(insight)
library(rstanarm)
#> Loading required package: Rcpp
#> Warning: package 'Rcpp' was built under R version 4.0.2
#> This is rstanarm version 2.21.1
#> - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
#> - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#>   options(mc.cores = parallel::detectCores())
model <- stan_glm(vs ~ mpg + cyl, data = mtcars, refresh=0, family="binomial")
get_priors(model)
#> Error in `$<-.data.frame`(`*tmp*`, "parameter", value = c("(Intercept)", : replacement has 3 rows, data has 2
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

using rstanarm_2.21.1, @strengejacke @mattansb can you reproduce?

**Comment by strengejacke** [comment] 2020-07-21 10:49
Im installing rstanarm from source, will check.

**Comment by strengejacke** [comment] 2020-07-21 11:06
> The default prior on the intercept is different than it was in rstanarm <= 2.19.3 for stan_glm, stan_glmer, etc.

Its _always_ **great** to have a proper maintained **NEWS** files!

**Comment by DominiqueMakowski** [comment] 2020-07-21 11:08
![](https://media.giphy.com/media/jUwpNzg9IcyrK/giphy.gif)

**Comment by strengejacke** [comment] 2020-07-21 11:23
The issue is actually than `merge()` somehow behaves strange... One df with 1 row, one with 2 rows, and the merged df is only 2 rows?

``` r
x1 <- structure(list(dist = "normal", location = "0", scale = "2.5"), class = "data.frame", row.names = c(NA, -1L))
x2 <- structure(list(dist = c("normal", "normal"), location = c("0", "0"), 
                     scale = c("2.5", "2.5"), adjusted_scale = c("0.414803641643042", "1.39983744766986")), 
                class = "data.frame", row.names = c(NA, -2L))

merge(x1, x2, all = TRUE)
#>     dist location scale    adjusted_scale
#> 1 normal        0   2.5 0.414803641643042
#> 2 normal        0   2.5  1.39983744766986
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any ideas how to get a df with 3 rows?

**Comment by DominiqueMakowski** [comment] 2020-07-21 11:26
the first one x1 corresponds to the intercept right? Maybe it needs to be added something like `x1$adjusted_scale <- x1$scale` ?

**Comment by DominiqueMakowski** [comment] 2020-07-21 11:26
or `merge(as.data.frame(x1), as.data.frame(x2), all = TRUE)`

**Comment by mattansb** [comment] 2020-07-21 11:30
I can't update `rstanarm` 🤷‍♂️

**Comment by strengejacke** [comment] 2020-07-21 11:39
> merge(as.data.frame(x1), as.data.frame(x2), all = TRUE)

Doesn't work. Will find missing columns and add them as NA.

**Comment by strengejacke** [comment] 2020-07-21 12:17
Please check, I hope this fix still works with other/older models/rstanarm versions?

**Closed** 2020-07-21 12:16 UTC
Labels: bug :bug:

**Comment by DominiqueMakowski** [comment] 2020-07-21 12:25
seems to work!! 👌
