### ISSUE TITLE
`get_predicted` ordinal missing standard errors for MASS models

### ISSUE THREAD

**Issue by krassowski** [easystats/insight#597] opened 2022-07-25 12:35 UTC
Would it be possible to extract standard errors in [`get_predicted.rlm` and `get_predicted.polr`](https://github.com/easystats/insight/blob/2cc5790a142920150ab348d4648953f79d6da662/R/get_predicted_ordinal.R#L106-L132
)?

It looks like [`get_predictions_lrm`](https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_lrm.R) mentioned in https://github.com/easystats/insight/issues/315#issuecomment-793518243 and related [`get_predictions_polr`](https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_polr.R) do that, but the implementation in `insight` does not, even though `get_predicted.clm` does extract SE. Was this just an accidental omission, or deliberate?

**Comment by bwiernik** [comment] 2022-07-25 14:05
It's likely that this model class just needs some special, non-default handling. Can you give a reproducible example for this model?

**Comment by krassowski** [comment] 2022-07-25 14:26
`rlm` - seems easy to add it:

```R
mod <- MASS::rlm(mpg ~ hp + factor(cyl), mtcars)
insight::get_predicted(mod)
predict(mod, se.fit=TRUE)
```

`polr` - this one requires manual computation of SE as `MASS::predict.polr` is rather rudimentary:

```R
data(housing, package = "MASS")
m1 <- MASS::polr(Sat ~ Infl + Type + Cont, data = housing, weights = Freq)
insight::get_predicted(m1)
```

**Comment by vincentarelbundock** [comment] 2022-07-30 19:00
Thanks for the report. I opened a pull request to add support for standard errors and confidence intervals in `rlm` models. It was very easy: 

https://github.com/easystats/insight/pull/601

Unfortunately, I think that adding CI and standard errors for `polr` models would be very hard. Since the `predict` method shipped with `MASS` does not produce standard errors, we would have to write a custom function ourselves, or implement delta method functionality ourselves. I've done that for `marginaleffects` and it took me a while. My recommendation is that we should leave this out of scope for `insight`, which has so far mainly been focused on *access* to information stored in model objects (see CRAN description).

FWIW, here's what it looks like in `marginaleffects`:

``` r
library(MASS)
library(marginaleffects)

mod <- polr(factor(gear) ~ hp + wt, data = mtcars)

predictions(mod, type = "probs") |> head()
#> 
#> Re-fitting to get Hessian
#>   rowid  type group predicted  std.error gear  hp    wt
#> 1     1 probs     3 0.2043263 0.09944805    4 110 2.620
#> 2     2 probs     3 0.3739230 0.11941360    4 110 2.875
#> 3     3 probs     3 0.1201170 0.08030641    4  93 2.320
#> 4     4 probs     3 0.6479346 0.12559777    3 110 3.215
#> 5     5 probs     3 0.4934684 0.12874838    3 175 3.440
#> 6     6 probs     3 0.8215874 0.10528346    3 105 3.460
```

**Comment by vincentarelbundock** [comment] 2022-07-30 20:21
Merged, so I am going to close this now.

Anyone should feel free to open a new `MASS::polr`-specific issue if they want to initiate a discussion **and** are ready to invest many hours to implement a solution.

**Closed by vincentarelbundock** 2022-07-30 20:21 UTC

**Comment by strengejacke** [comment] 2022-07-30 22:09
I have implemented this in _ggeffects_ as well, I'll may look into this issue the next days

**Comment by strengejacke** [comment] 2022-07-31 13:05
``` r
library(MASS)
library(nnet)

m1 <- polr(factor(gear) ~ hp, data = mtcars)
m2 <- multinom(factor(gear) ~ hp, data = mtcars)
#> # weights:  9 (4 variable)
#> initial  value 35.155593 
#> iter  10 value 21.335880
#> final  value 21.334338 
#> converged

nd <- data.frame(hp = c(100, 120))

insight::get_predicted(m1, data = nd) |> as.data.frame()
#> 
#> Re-fitting to get Hessian
#>   Row Response  hp Predicted     CI_low   CI_high
#> 1   1        3 100 0.4039626 0.17059047 0.6907197
#> 2   2        3 120 0.4425208 0.15950735 0.7685289
#> 3   1        4 100 0.4155521 0.17747827 0.7008623
#> 4   2        4 120 0.3992025 0.13708088 0.7353954
#> 5   1        5 100 0.1804853 0.06264781 0.4205305
#> 6   2        5 120 0.1582767 0.04302206 0.4402504

insight::get_predicted(m2, data = nd) |> as.data.frame()
#>   Row Response  hp  Predicted     CI_low    CI_high
#> 1   1        3 100 0.27256906 0.27256906 0.27256906
#> 2   2        3 120 0.48800054 0.48800054 0.48800054
#> 3   1        4 100 0.66864845 0.66864845 0.66864845
#> 4   2        4 120 0.39548865 0.39548865 0.39548865
#> 5   1        5 100 0.05878248 0.05878248 0.05878248
#> 6   2        5 120 0.11651080 0.11651080 0.11651080
```

<sup>Created on 2022-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We should also check support for "brmultinom", "bracl", "mixor" and "fixest".

**Comment by strengejacke** [comment] 2022-07-31 13:20
ups, just saw, isn't working for nnet::multinom...

**Comment by vincentarelbundock** [comment] 2022-07-31 13:22
Daniel to the rescue! Looks like I overestimated the difficulty of the task when someone like him is involved ;)

**Comment by vincentarelbundock** [comment] 2022-07-31 13:28
> ups, just saw, isn't working for nnet::multinom...

@strengejacke I have not investigated, but in this comment someone claims that the `inverse_link()` produces the wrong result for `multinom` (softmax) : https://github.com/vincentarelbundock/marginaleffects/issues/404#issuecomment-1186612749

**Comment by strengejacke** [comment] 2022-07-31 13:57
See my comment here:
https://github.com/easystats/insight/commit/99c14252be2e33d0cebeb1c5e749802a9625943b#commitcomment-79869045
