### ISSUE TITLE
feature request survival models

### ISSUE THREAD

**Issue by sbalci** [easystats/insight#110] opened 2019-06-04 10:27 UTC
Would you please support models for Kaplan-Meier survivals:

```
km_fit <- survfit(Surv(time, status) ~ feature, data = data)
km_fit
> Call: survfit(formula = Surv(time, status) ~ feature, data = data)
>      n  events  median 0.95LCL 0.95UCL
>     75      70      12      10      17 
```

I would really like to to extract specific time points data from survival models for reproducible reports. 

Example: I want to extract `time` and `survival` from the model output below.

**`12` months survival is `0.48`.**

```
summary(km_fit, times = c(12,36,60))
>Call: survfit(formula = Surv(time, status) ~ feature, data = data)
> time n.risk n.event survival std.err lower 95% CI upper 95% CI
>   12     41      39   0.4800  0.0577       0.3793        0.607
>   36     14      21   0.1981  0.0463       0.1253        0.313
>   60      2       9   0.0419  0.0271       0.0118          0.149
```

**Comment by strengejacke** [comment] 2019-06-05 12:03
Do you have a reproducible example for your model?

**Comment by sbalci** [comment] 2019-06-05 13:13
Thank you. Below is the reprex with `lung` data in `survival` package.

As an example I would like to get the highlighted information from the results:
In `sex=1` `1` year survival is `0.3361` 95%CI (`0.261` - `0.433`) ,  `2` year survival is `0.0781` 95%CI (`0.039` - `0.156`).

```
library(survival)
km_fit <- survfit(Surv(time, status) ~ sex, data = lung)
km_fit
#> Call: survfit(formula = Surv(time, status) ~ sex, data = lung)
#> 
#>         n events median 0.95LCL 0.95UCL
#> sex=1 138    112    270     212     310
#> sex=2  90     53    426     348     550

summary(km_fit, times = c(0.5, 1, 2), scale = 365.25)
#> Call: survfit(formula = Surv(time, status) ~ sex, data = lung)
#> 
#>                 sex=1 
#>  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#>   0.5     86      51   0.6298  0.0412        0.554        0.716
#>   1.0     35      34   0.3361  0.0434        0.261        0.433
#>   2.0      7      24   0.0781  0.0276        0.039        0.156
#> 
#>                 sex=2 
#>  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#>   0.5     70      15    0.831  0.0399       0.7559        0.913
#>   1.0     30      21    0.526  0.0597       0.4215        0.658
#>   2.0      6      14    0.187  0.0621       0.0978        0.359
```

**Comment by DominiqueMakowski** [comment] 2019-06-05 15:01
I have the feeling that for the confidence intervals, it won't be implemented in this package  (as it doesn't have a function designed to retrieve the CI).  So the idea would be to retrieve things like the coefficients, the parameters' names, the outcome's variable name etc. 

@sbalci would you be able to guide us; In your model above, what should in your opinion these three functions return:

- [find_parameters](https://easystats.github.io/insight/reference/find_parameters.html)
- [find_predictors](https://easystats.github.io/insight/reference/find_predictors.html)
- [find_response](https://easystats.github.io/insight/reference/find_response.html)

It seems like `"sex"` here is a predictor...?

Thanks!

**Comment by sbalci** [comment] 2019-06-05 19:15
Hi,
Thank you for your interest. I will be happy to help as far as I can. I will try to explain the details of the analysis. I hope it helps.

As you mentioned 'sex' is a predictor here.
The parameters would be 'time' and 'status' in the data set. 
The response is the cumulative percentage of cases that are alive (status != 2) at the end of given time. (See data description [here](https://stat.ethz.ch/R-manual/R-devel/library/survival/html/lung.html))

- I think you may get the details from the list 'km_fit' as follows:

```
# View fit
View(km_fit)
```
<img width="787" alt="Ekran Resmi 2019-06-05 21 22 28" src="https://user-images.githubusercontent.com/7208830/58980034-1d8d5c80-87d8-11e9-9d6b-fb7ddd975c4f.png">



- You may get formula as follows:

```
# Get formula
km_fit[["call"]][["formula"]]
#> Surv(time, status) ~ sex
# Get formula 2
km_fit[["call"]]
#> survfit(formula = Surv(time, status) ~ sex, data = lung)
```


- You may get other results including 95%CI as follows: 

```
library(tidyverse)
# make a dataframe from fit list
fitDF <- bind_cols(
time = km_fit[["time"]],
n.risk = km_fit[["n.risk"]],
n.event = km_fit[["n.event"]],
n.censor = km_fit[["n.censor"]],
surv = km_fit[["surv"]],
lower = km_fit[["lower"]],
upper = km_fit[["upper"]],
) %>% 
  mutate(
    timeyear = time / 365.25
  )


# this gives the result for the time = 0.5
fitDF[which.min(abs(fitDF$timeyear - 0.5)),]
#> # A tibble: 1 x 8
#>    time n.risk n.event n.censor  surv lower upper timeyear
#>   <dbl>  <dbl>   <dbl>    <dbl> <dbl> <dbl> <dbl>    <dbl>
#> 1   183     86       1        0 0.622 0.547 0.709    0.501

# this gives the result for the time = 1
fitDF[which.min(abs(fitDF$timeyear - 1)),]
#> # A tibble: 1 x 8
#>    time n.risk n.event n.censor  surv lower upper timeyear
#>   <dbl>  <dbl>   <dbl>    <dbl> <dbl> <dbl> <dbl>    <dbl>
#> 1   364     36       1        0 0.336 0.261 0.433    0.997

# this gives the result for the time = 2
fitDF[which.min(abs(fitDF$timeyear - 2)),]
#> # A tibble: 1 x 8
#>    time n.risk n.event n.censor  surv  lower upper timeyear
#>   <dbl>  <dbl>   <dbl>    <dbl> <dbl>  <dbl> <dbl>    <dbl>
#> 1   731      6       1        0 0.156 0.0743 0.328     2.00

```

- But I could not split these results based on 'sex' variable. Maybe I should have splitted the data before the analysis.

Thank you for consideration.

**Comment by strengejacke** [comment] 2019-06-05 20:33
I have added support for `survfit` objects, as fas as it was possible. However, what you like to do is beyond the scope of this package. _insight_ allows you to access general model information like formula, terms/predictors etc. 

But your intention is to get concrete _results_ from the survfit-object, in particular predicted survival. If I'm right with my guess, I think the [ggeffects-package](https://strengejacke.github.io/ggeffects/) might help you, and you probably need to fit a cox-proportional-hazard model. See examples [here](https://strengejacke.github.io/ggeffects/articles/ggeffects.html#survival-models) and [here](https://strengejacke.github.io/ggeffects/articles/introducion_plotmethod.html#survival-models).

``` r
library(survival)
library(ggeffects)

data("lung")
m <- coxph(Surv(time, status) ~ sex + age + ph.ecog, data = lung)

# risk score
ggpredict(m, "sex")
#> 
#> # Predicted risk scores
#> # x = sex
#> 
#>  x predicted std.error conf.low conf.high
#>  1     1.245     0.067    1.093     1.418
#>  2     0.716     0.101    0.587     0.874
#> 
#> Adjusted for:
#> *     age = 62.46
#> * ph.ecog =  0.95
#> Standard errors are on link-scale (untransformed).

# predicted survial
ggpredict(m, "sex", type = "surv")
#> 
#> # Probability of Survival
#> # x = time
#> 
#> # sex = 1
#>     x predicted conf.low conf.high
#>     5     0.995    0.984     1.000
#>   144     0.784    0.717     0.856
#>   202     0.620    0.540     0.712
#>   276     0.515    0.431     0.616
#>   364     0.334    0.252     0.443
#>  1022     0.024    0.007     0.090
#> 
#> # sex = 2
#>     x predicted conf.low conf.high
#>     5     0.997    0.991     1.000
#>   144     0.869    0.817     0.924
#>   202     0.759    0.685     0.842
#>   276     0.683    0.596     0.783
#>   364     0.532    0.430     0.659
#>  1022     0.118    0.048     0.291
#> 
#> Adjusted for:
#> *     age = 62.46
#> * ph.ecog =  0.95
```

<sup>Created on 2019-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sbalci** [comment] 2019-06-06 06:36
Thank you very much. 
I will check the `ggeffects` package.
I have also found an easier way to get `survfit` information [here](https://stackoverflow.com/questions/43419385/how-to-export-survfit-output-as-a-csv-table).
Best wishes.

**Closed** 2019-06-06 07:00 UTC
Labels: enhancement

**Comment by pdwaggoner** [comment] 2019-06-06 12:42
@sbalci - I know this issue is closed, but if you'd just like to grab basic output from a survival model, you could try a few lines of simple code, like the following: 

```{r}
ts <- survfit(model) # fit model
h <- ts$cumhaz # cumulative hazard rates
survival <- ts$surv # survival probabilities 
survival_df <- cbind(time = ts$time, hazard = h, survival = ts$surv) # combine them as a useful df
```

Not sure if this is what you're looking for, but based on the stackoverflow solution you shared, this seems to be similar, by just stored certain quantities of interest and combining them as a df. Anyway, for whatever this may be worth, good luck!

**Comment by sbalci** [comment] 2019-11-11 12:37
I am adding the following code if anyone is interested in the future:

```r
library(survival)

km_fit <- survfit(Surv(time, status) ~ sex, data = lung)

km_fit_summary <- summary(km_fit, times = c(0.5, 1, 2), scale = 365.25)

km_fit_df <- as.data.frame(km_fit_summary[c("strata", "time", "n.risk", 
"n.event", "surv", "std.err", "lower", "upper")])

km_fit_df %>% 
    dplyr::mutate(
        description = 
            glue::glue(
                "When {strata}, {time} month survival is {scales::percent(surv)} [{scales::percent(lower)}-{scales::percent(upper)}, 95% CI]."
            )
    ) %>% 
    dplyr::select(description) %>% 
    pull()
```

```
> When sex=1, 0.5 month survival is 63.0% [55.4%-71.6%, 95% CI].
> When sex=1, 1 month survival is 33.6% [26.1%-43.3%, 95% CI].
> When sex=1, 2 month survival is 7.8% [3.9%-15.6%, 95% CI].
> When sex=2, 0.5 month survival is 83.1% [75.6%-91.3%, 95% CI].
> When sex=2, 1 month survival is 52.6% [42.1%-65.8%, 95% CI].
> When sex=2, 2 month survival is 18.7% [9.8%-35.9%, 95% CI].
```
