### ISSUE TITLE
`get_modelmatrix()` breaks when `data` includes only one factor level

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#612] opened 2022-08-14 21:30 UTC
`get_modelmatrix()` breaks when the `data` argument does not include at least two factor levels:

``` r
library(insight)

dat <- mtcars
dat$cyl <- factor(dat$cyl)
mod <- glm(vs ~ cyl, data = dat, family = binomial)

# works
get_modelmatrix(mod, data = head(dat, 3))
#>               (Intercept) cyl6
#> Mazda RX4               1    1
#> Mazda RX4 Wag           1    1
#> Datsun 710              1    0
#> attr(,"assign")
#> [1] 0 1
#> attr(,"contrasts")
#> attr(,"contrasts")$cyl
#> [1] "contr.treatment"

# breaks
get_modelmatrix(mod, data = head(dat, 1))
#> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels
```

This is of course because `stats::model.matrix()` does not support this either:

``` r
model.matrix(mod, data = head(dat, 1))
#> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels
```

Would it make sense for `get_modelmatrix()` to include some guardrails, and perhaps pad/unpad the data with missing factors when necessary?

First reported here: <https://github.com/vincentarelbundock/marginaleffects/issues/455>

**Comment by strengejacke** [comment] 2022-08-14 21:35
Possible duplicate of #316

**Comment by vincentarelbundock** [comment] 2022-08-14 21:37
hahaha

so, shall we pad?

**Comment by strengejacke** [comment] 2022-08-14 21:39
(and I think we haven't even touched [contrasts](https://github.com/strengejacke/ggeffects/blob/fef45e768f8345bae81137db6d583cf038221048/R/vcov.R#L264))

**Comment by bwiernik** [comment] 2022-08-14 23:52
I suggest we pad the model matrix with rows containing all factor levels from the original data, make the matrix, then remove those rows. That would be an awesome improvement on model.matrix() functionality

**Comment by vincentarelbundock** [comment] 2022-08-15 00:07
I can give this a shot eventually.

**Closed** 2022-08-15 02:33 UTC

**Comment by strengejacke** [comment] 2022-08-15 05:50
@vincentarelbundock should we ass the pad/unpad stuff to other `get_modelmatrix()` methods, too?

**Comment by strengejacke** [comment] 2022-08-15 10:22
edit, "add", not "ass" 😬

**Comment by vincentarelbundock** [comment] 2022-08-15 10:29
> @vincentarelbundock should we add the pad/unpad stuff to other `get_modelmatrix()` methods, too?

I tried with a `merMod` object: a dataset with an "incomplete" factor produced a matrix without issues, even without padding. So it seems like this may only affect certain models.

I actually debated including this only in a new `get_modelmatrix.lm/glm` method instead of `.default`, but in the end I thought the cost was pretty low.

Ideally we would check all models one-by-one, but I probably won't have time this week, and this is probably safe enough to play it by ear.

**Comment by strengejacke** [comment] 2022-08-15 10:33
ok, sounds good to me. Else,. I'd suggest we just create a generic `.pad_modelmatrix_unpad()` method, where we copy the three codeline that call pad, model matrix and unpad... This one could replace all single calls to `model.matrix()`.

**Comment by vincentarelbundock** [comment] 2022-08-15 10:44
Agreed on a generic function. Not convinced we should replace all of the calls. There is a performance penalty, so we should do this only when we know it is necessary.

**Comment by strengejacke** [comment] 2022-08-15 11:08
no, not all yet, but as you said, whenever we face those issues...

**Comment by vincentarelbundock** [comment] 2022-08-15 11:18
Oh, I just remembered why I kept the two functions separate: If you look at all the methods, you'll see that a lot of objects require a bunch of processing, and not just a `stats::model.matrix()` call. So for those, it might be useful to have two separate `pad`/`unpad` functions, since we can insert them at the right place in the code.
