### ISSUE TITLE
Multiple CIs don't work in ci() + other minor

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#322] opened 2021-03-15 02:36 UTC
For some reason cis don't work with multiple intervals, which is strange ^^

``` r
bayestestR::describe_posterior(rnorm(100), ci = c(0.9, 0.80))
#> Summary of Posterior Distribution
#> 
#> Parameter | Median |        90% CI |        80% CI |     pd |          ROPE | % in ROPE
#> ---------------------------------------------------------------------------------------
#> Posterior |  -0.05 | [-1.40, 1.51] | [-1.02, 1.27] | 51.00% | [-0.10, 0.10] |     6.67%

bayestestR::ci(rnorm(100), ci = c(0.9, 0.80))
#> Equal-Tailed Interval
#> 
#> 90% ETI       |       80% ETI
#> -----------------------------
#> [-1.72, 1.93] |              
#>               | [-1.31, 1.32]
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

----

- rehape_ci doens't work from wide to long (anymore?):

``` r
insight::reshape_ci(bayestestR::describe_posterior(iris, ci = c(0.9, 0.80)))
#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.

#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.

#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.
#>      Parameter Median CI_low_0.9 CI_high_0.9 CI_low_0.8 CI_high_0.8 pd ROPE_CI
#> 1 Sepal.Length   5.80        4.4         6.9        4.9         6.9  1    0.89
#> 2  Sepal.Width   3.00        2.4         3.8        2.5         3.6  1    0.89
#> 3 Petal.Length   4.35        1.1         5.8        1.3         5.5  1    0.89
#> 4  Petal.Width   1.30        0.2         2.3        0.1         1.9  1    0.89
#>   ROPE_low ROPE_high ROPE_Percentage
#> 1     -0.1       0.1               0
#> 2     -0.1       0.1               0
#> 3     -0.1       0.1               0
#> 4     -0.1       0.1               0
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

- Do we fix the number of digits? in the above example it's shown as 0.8, but we "requested" 0.80. It would be annoying to deparse it somehow, so maybe we should simply fix the number of digits to a lower minimum? so that it's always minimum 2 digits or something?

**Comment by strengejacke** [comment] 2021-03-15 07:08
Your first example works as intendend?

**Comment by DominiqueMakowski** [comment] 2021-03-15 07:10
yes it works with describe_posterior

**Comment by strengejacke** [comment] 2021-03-15 07:18
1. your first examples works as intended
2. second case should be fixed now (was indeed a fix in the original functions, as I didn't change any code)
3. your re-re-shaping works as well. You were looking at the _print output_, not the underlying data frame:

``` r
x <- bayestestR::describe_posterior(iris, ci = c(0.9, 0.80))
#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.

#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.

#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.

as.data.frame(x)
#>      Parameter Median  CI CI_low CI_high pd ROPE_CI ROPE_low ROPE_high
#> 5 Sepal.Length   5.80 0.9    4.4     6.9  1    0.89     -0.1       0.1
#> 6 Sepal.Length   5.80 0.8    4.9     6.9  1    0.89     -0.1       0.1
#> 7  Sepal.Width   3.00 0.9    2.4     3.8  1    0.89     -0.1       0.1
#> 8  Sepal.Width   3.00 0.8    2.5     3.6  1    0.89     -0.1       0.1
#> 1 Petal.Length   4.35 0.9    1.1     5.8  1    0.89     -0.1       0.1
#> 2 Petal.Length   4.35 0.8    1.3     5.5  1    0.89     -0.1       0.1
#> 3  Petal.Width   1.30 0.9    0.2     2.3  1    0.89     -0.1       0.1
#> 4  Petal.Width   1.30 0.8    0.1     1.9  1    0.89     -0.1       0.1
#>   ROPE_Percentage
#> 5               0
#> 6               0
#> 7               0
#> 8               0
#> 1               0
#> 2               0
#> 3               0
#> 4               0

insight::reshape_ci(x)
#>      Parameter Median CI_low_0.9 CI_high_0.9 CI_low_0.8 CI_high_0.8 pd ROPE_CI
#> 1 Sepal.Length   5.80        4.4         6.9        4.9         6.9  1    0.89
#> 2  Sepal.Width   3.00        2.4         3.8        2.5         3.6  1    0.89
#> 3 Petal.Length   4.35        1.1         5.8        1.3         5.5  1    0.89
#> 4  Petal.Width   1.30        0.2         2.3        0.1         1.9  1    0.89
#>   ROPE_low ROPE_high ROPE_Percentage
#> 1     -0.1       0.1               0
#> 2     -0.1       0.1               0
#> 3     -0.1       0.1               0
#> 4     -0.1       0.1               0

x2 <- insight::reshape_ci(x)
insight::reshape_ci(x2)
#>      Parameter Median  CI CI_low CI_high pd ROPE_CI ROPE_low ROPE_high
#> 1 Petal.Length   4.35 0.8    1.3     5.5  1    0.89     -0.1       0.1
#> 2 Petal.Length   4.35 0.9    1.1     5.8  1    0.89     -0.1       0.1
#> 3  Petal.Width   1.30 0.8    0.1     1.9  1    0.89     -0.1       0.1
#> 4  Petal.Width   1.30 0.9    0.2     2.3  1    0.89     -0.1       0.1
#> 5 Sepal.Length   5.80 0.8    4.9     6.9  1    0.89     -0.1       0.1
#> 6 Sepal.Length   5.80 0.9    4.4     6.9  1    0.89     -0.1       0.1
#> 7  Sepal.Width   3.00 0.8    2.5     3.6  1    0.89     -0.1       0.1
#> 8  Sepal.Width   3.00 0.9    2.4     3.8  1    0.89     -0.1       0.1
#>   ROPE_Percentage
#> 1               0
#> 2               0
#> 3               0
#> 4               0
#> 5               0
#> 6               0
#> 7               0
#> 8               0
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment] 2021-03-15 07:20
reshaping CIs is done insight the format-function, thus you can't change the output. If you prefer having an option to split output by CIs, we could/should add this (e.g. new argument) in the related format-function in _bayestestR_.

**Closed** 2021-03-22 13:27 UTC
Labels: 3 investigators :grey_question::question:
