### ISSUE TITLE
get_data(), preserving "factor" class in dataframes

### ISSUE THREAD

**Issue by ebkreyson** [easystats/insight#665] opened 2022-10-10 22:51 UTC
Recently ran into an issue in R using `marginaleffects::plot_cap()`, which makes use of `insight::get_data()`. Specifically, I encountered the issue when using a plm object, which calls `insight::get_data.plm()`. 

Long story short, the dataframe returned by `get_data.plm()` converts factors to characters due to your use of `cbind()`. Looking at the [source code](https://github.com/easystats/insight/blob/main/R/get_data.R), the snippet of code that uses `cbind()` starts at Line 823:

```
  if (!is.null(index)) {
    original_data <- .recover_data_from_environment(x)
    keep <- intersect(index, colnames(original_data))
    if (length(keep)) {
      mf <- cbind(mf, original_data[, keep, drop = FALSE])
      model_terms <- c(model_terms, keep)
    }
  }
```

The exact issue within the context of the "marginaleffects" package has been posted [here](https://github.com/vincentarelbundock/marginaleffects/issues/505), but I want to keep this relevant to "insight". Specifically, would it be possible to use `data.frame()` instead of `cbind()`? Both should accomplish the same task but the former would preserve the original data structure of each column from `mf` as it's defined in the code above.

One last thing to note is that this proposed fix could be applied to other `get_data()` subfunctions that use `cbind()`. I'm only personally dealing with plm objects, so I can't say if the fix would be feasible or even beneficial for other structures, but it's worth considering.

**Comment by vincentarelbundock** [comment] 2022-10-10 23:18
MWE for the record:

```r
library(plm)
library(insight)

ID <- rep(c('A','B','C','D','E','F'), each=4)
Time <- rep(c(1:4), 6)
factor1 <- rep(c("c","0","1"), each=8)
factor2 <- rep(c(0, 0, 1, 1), 6)
y <- c(
  rep(c(5, 5, 5, 5), 2),
  rep(c(2, 2, 10, 20), 2),
  rep(c(3, 3, 15, 5), 2)
)
df <- as.data.frame(cbind(ID,Time,factor1,factor2,y))
df$y <- as.numeric(df$y)
df$factor1 <- as.factor(df$factor1)
df$factor1 <- relevel(df$factor1, ref = "c")
df$factor2 <- as.factor(df$factor2)

mod <- plm(y ~ factor1 * factor2, data = df, model = "random", index = c("ID","Time"))

get_data(mod) |> str()
#> 'data.frame':    24 obs. of  5 variables:
#>  $ y      : num  5 5 5 5 5 5 5 5 2 2 ...
#>  $ factor1: chr  "c" "c" "c" "c" ...
#>  $ factor2: chr  "0" "0" "1" "1" ...
#>  $ ID     : chr  "A" "A" "A" "A" ...
#>  $ Time   : chr  "1" "2" "3" "4" ...
#>  - attr(*, "is_subset")= logi FALSE
```

**Comment by strengejacke** [comment] 2022-10-11 09:24
I think the issue is from some lines before:

```r
mf <- as.data.frame(lapply(mf, as.vector))
```

Should be fixed with the last commit. The idea is to remove these special class attributes, which might cause problems.

**Comment by strengejacke** [comment] 2022-10-11 09:26
``` r
library(plm)
library(insight)

ID <- rep(c('A','B','C','D','E','F'), each=4)
Time <- rep(c(1:4), 6)
factor1 <- rep(c("c","0","1"), each=8)
factor2 <- rep(c(0, 0, 1, 1), 6)
y <- c(
  rep(c(5, 5, 5, 5), 2),
  rep(c(2, 2, 10, 20), 2),
  rep(c(3, 3, 15, 5), 2)
)
df <- as.data.frame(cbind(ID, Time, factor1, factor2, y))
df$y <- as.numeric(df$y)
df$factor1 <- as.factor(df$factor1)
df$factor1 <- relevel(df$factor1, ref = "c")
df$factor2 <- as.factor(df$factor2)

mod <- plm(y ~ factor1 * factor2, data = df, model = "random", index = c("ID","Time"))
#> Warning in summary.lm(object, ...): essentially perfect fit: summary may be
#> unreliable
get_data(mod) |> str()
#> 'data.frame':    24 obs. of  5 variables:
#>  $ y      : num  5 5 5 5 5 5 5 5 2 2 ...
#>  $ factor1: Factor w/ 3 levels "c","0","1": 1 1 1 1 1 1 1 1 2 2 ...
#>   ..- attr(*, "index")=Classes 'pindex' and 'data.frame':    24 obs. of  2 variables:
#>   .. ..$ ID  : Factor w/ 6 levels "A","B","C","D",..: 1 1 1 1 2 2 2 2 3 3 ...
#>   .. ..$ Time: Factor w/ 4 levels "1","2","3","4": 1 2 3 4 1 2 3 4 1 2 ...
#>  $ factor2: Factor w/ 2 levels "0","1": 1 1 2 2 1 1 2 2 1 1 ...
#>   ..- attr(*, "index")=Classes 'pindex' and 'data.frame':    24 obs. of  2 variables:
#>   .. ..$ ID  : Factor w/ 6 levels "A","B","C","D",..: 1 1 1 1 2 2 2 2 3 3 ...
#>   .. ..$ Time: Factor w/ 4 levels "1","2","3","4": 1 2 3 4 1 2 3 4 1 2 ...
#>  $ ID     : chr  "A" "A" "A" "A" ...
#>  $ Time   : chr  "1" "2" "3" "4" ...
#>  - attr(*, "is_subset")= logi FALSE
```

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed** 2022-10-11 09:38 UTC
Labels: bug :bug:

**Comment by ebkreyson** [comment] 2022-10-11 13:24
Just tried the latest version, it's working as intended with real data. Thank you for your assistance on this.

**Comment by vincentarelbundock** [comment] 2022-10-11 13:40
Yes, thanks so much @strengejacke 

Was planning to help on this one, but things are a bit crazy over here these days...
