### ISSUE TITLE
sigma missing from get_parameters for brmsfit

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#268] opened 2020-12-15 16:12 UTC
```R
d <- data.frame(
  y = c(1:10, 7:20),
  g = c(rep("a", 10), rep("b", 14))
)

m <- brm(y ~ g, data = d)

head(as.data.frame(m))
#>   b_Intercept      b_gb    sigma      lp__
#> 1    5.959691  8.300159 3.530216 -69.02844
#> 2    4.079490 11.439245 4.299431 -71.28811
#> 3    5.098114  9.395647 4.899456 -70.67759
#> 4    7.403645  5.253382 3.190147 -71.29800
#> 5    5.202920  8.492960 5.345700 -71.40868
#> 6    6.531525  3.942267 3.722208 -73.59843

head(insight::get_parameters(m, effects = "all", component = "all"))
#>   b_Intercept      b_gb
#> 1    5.959691  8.300159
#> 2    4.079490 11.439245
#> 3    5.098114  9.395647
#> 4    7.403645  5.253382
#> 5    5.202920  8.492960
#> 6    6.531525  3.942267





data(sleep)

m <- brm(extra ~ group + (group | ID),
         data = sleep)

colnames(as.data.frame(m))
#>  [1] "b_Intercept"               "b_group2"                  "sd_ID__Intercept"          "sd_ID__group2"            
#>  [5] "cor_ID__Intercept__group2" "sigma"                     "r_ID[1,Intercept]"         "r_ID[2,Intercept]"        
#>  [9] "r_ID[3,Intercept]"         "r_ID[4,Intercept]"         "r_ID[5,Intercept]"         "r_ID[6,Intercept]"        
#> [13] "r_ID[7,Intercept]"         "r_ID[8,Intercept]"         "r_ID[9,Intercept]"         "r_ID[10,Intercept]"       
#> [17] "r_ID[1,group2]"            "r_ID[2,group2]"            "r_ID[3,group2]"            "r_ID[4,group2]"           
#> [21] "r_ID[5,group2]"            "r_ID[6,group2]"            "r_ID[7,group2]"            "r_ID[8,group2]"           
#> [25] "r_ID[9,group2]"            "r_ID[10,group2]"           "lp__" 

colnames(insight::get_parameters(m, effects = "all", component = "all"))
#>  [1] "b_Intercept"               "b_group2"                  "r_ID.1.Intercept."         "r_ID.2.Intercept."        
#>  [5] "r_ID.3.Intercept."         "r_ID.4.Intercept."         "r_ID.5.Intercept."         "r_ID.6.Intercept."        
#>  [9] "r_ID.7.Intercept."         "r_ID.8.Intercept."         "r_ID.9.Intercept."         "r_ID.10.Intercept."       
#> [13] "r_ID.1.group2."            "r_ID.2.group2."            "r_ID.3.group2."            "r_ID.4.group2."           
#> [17] "r_ID.5.group2."            "r_ID.6.group2."            "r_ID.7.group2."            "r_ID.8.group2."           
#> [21] "r_ID.9.group2."            "r_ID.10.group2."           "sd_ID__Intercept"          "sd_ID__group2"            
#> [25] "cor_ID__Intercept__group2"
```

**Comment by strengejacke** [comment] 2020-12-15 16:17
See discussion here:
https://github.com/easystats/bayestestR/issues/338

We may close this in favor of the issue in _bayestestR_?

**Comment by mattansb** [comment] 2020-12-15 16:40
But is this also the expected behavior?

```R
colnames(insight::get_parameters(m, component = "sigma"))
#> character(0)
```

**Comment by strengejacke** [comment] 2020-12-15 16:45
Based on the discussion in https://github.com/easystats/bayestestR/issues/338 and #232, I'd rather say it is _requested_ behaviour, so I reverted the implementation of including sigma (https://github.com/easystats/insight/commit/1bfd224ec0701f2f2299184e6621039be2339e30).

**Comment by mattansb** [comment] 2020-12-16 04:10
:/

Shouldn't sigma (or other distribution parameters) be returned at least when they are specifically requested? (`component = "sigma"`)

**Comment by DominiqueMakowski** [comment] 2020-12-16 06:53
what about `get_sigma()`

**Comment by mattansb** [comment] 2020-12-16 07:05
Then the "sigma" option should be dropped from the `get_parameters` docs.

**Comment by DominiqueMakowski** [comment] 2020-12-16 07:08
Maybe allowing for `insight::get_parameters(m, component = "sigma")` or `insight::get_parameters(m, component = "aux")` isn't a bad idea after all

**Comment by mattansb** [comment] 2020-12-16 07:18
Maybe we should default not to "all", but to "all_location"? As in, all the location-parameters in the model?

- Location parameters
  - Conditional
  - smooth_terms (?)
  - ZI / zero_inflated
  - simplex (?)
- Distributional parameters
  - dispersion
  - sigma
  - **other `dpar` parameters**

**Comment by mattansb** [comment] 2020-12-16 07:20
As for `dpar`, for example here we need the beta and sigma parameters:

```R
library(brms)

d <- data.frame(y = 1:10)

m <- brm(y ~ 1, family = exgaussian(), data = d)
class(m)

colnames(insight::get_parameters(m, component = "all"))
#> [1] "b_Intercept"

insight::get_sigma(m)
#> [1] 3.853512
#> attr(,"class")
#> [1] "insight_aux" "numeric"

```

**Comment by strengejacke** [comment] 2020-12-16 08:41
I think this is an easy change, we can make `insight::get_parameters(m, component = "all")` return sigma as well, and we could add two other "components", namely `"location"` and `"distributional"`. You just need to prepare effectsize first, since this will break (bayestestR and parameters will not, I think).

**Comment by strengejacke** [comment] 2020-12-16 08:43
Maybe, for now, we can add the `"location"` option as an alias for `"all"`, then we check all packages if these work, and then later we make `"all"` include sigma?

**Comment by mattansb** [comment] 2020-12-16 08:44
I don't think this should affect `effectsize`.

**Comment by DominiqueMakowski** [comment] 2020-12-16 08:49
> * Location parameters
>   
>   * Conditional
>   * smooth_terms (?)
>   * ZI / zero_inflated
>   * simplex (?)
> * Distributional parameters
>   
>   * dispersion
>   * sigma
>   * **other `dpar` parameters**

We need to add this nice breakdown in the docs

**Comment by strengejacke** [comment] 2020-12-16 08:53
> I don't think this should affect `effectsize`.

https://github.com/easystats/insight/issues/232#issuecomment-699626835 - that was one of the main reasons why I reverted that change.

**Comment by mattansb** [comment] 2020-12-16 08:56
But if the new default is to only give the `location` parameters, this wont break.
But I will test after the change is made here (:

**Comment by strengejacke** [comment] 2020-12-16 09:34
At the moment, we have following elements, which will be returned (if present), when default is `"all"`:

```r
  elements <- c("conditional", "conditional2", "conditional3", "precision",
                "nonlinear", "random", "zero_inflated", "zero_inflated_random",
                "dispersion", "instruments", "interactions", "simplex",
                "smooth_terms", "sigma", "nu", "tau", "correlation", "slopes",
                "cluster", "extra", "scale", "marginal")
```

**Comment by strengejacke** [comment] 2020-12-16 09:35
How can we match this with "location"?

**Comment by mattansb** [comment] 2020-12-16 09:53
These are all the options for `brmsfit`???

**Comment by strengejacke** [comment] 2020-12-16 10:00
No, in general, depending on the model class. E.g., "instruments" is from FE regression (like felm, feisr, ...)

**Comment by strengejacke** [comment] 2020-12-16 10:01
I think tau and nu are for quantile regression

**Comment by mattansb** [comment] 2020-12-16 11:12
From what I know:

- "location"
  - "conditional"
  - "marginal"
  - "zero_inflated"
  - "zero_inflated_random"
  - "random" **(though there can be random `npar` in `brms`)**
  - "smooth_terms" **(though there can be smooth `npar` terms in `brms`)**
  - "conditional2" I think - what's this?
  - "conditional3" I think - what's this?
  - "instruments" I think - what's this?
- distributional
  - "dispersion"
  - "sigma"
  - **whichever one gives the `npar` from `brmsfit`???**


Don't know enough about these:
- "correlation" (is this from multivariate models? If so, I'd give this either in a 3rd category, or in "distributional", as it is multivariate distributional).
- "precision"
- "nonlinear"
- "interactions"
- "simplex"
- "nu"
- "tau"
- "slopes"
- "cluster"
- "extra"
- "scale"

**Comment by strengejacke** [comment] 2020-12-16 13:43
> "conditional2" I think - what's this?
> "conditional3" I think - what's this?

There is a special case for "DirichletRegression" models...

> "instruments" I think - what's this?

As I wrote above, all FE regression stuff ("Instrumental Variables Regression")

**Comment by strengejacke** [comment] 2020-12-16 13:47
multivariate distributional).
- "precision" -> DirichletRegModel
- "nonlinear" -> nlmerMod
- "interactions" -> panelr-package, which has a part for "cross level interactions"
- "simplex" -> brms monotonic parameters
- "nu" -> gamlss models
- "tau" -> gamlss models
- "slopes" -> fixed effects individual slopes models (feisr package), 
- "cluster" -> for FE regression, some have a cluster part in the formula
- "extra" -> no longer used
- "scale" -> cumulative link models.

**Comment by strengejacke** [comment] 2020-12-16 15:05
Ok, I'll think about drafting new arguments, that work as a kind of "shortcut". However, would you suggest `component = "location"`, although `location` includes `effects`? (i.e. `effects = "all"`)

**Comment by mattansb** [comment] 2020-12-17 09:05
> although location includes effects? (i.e. effects = "all")

Not sure what you mean by this?

Also, which component would give the brms dpars?

**Comment by strengejacke** [comment] 2020-12-17 09:17
The API is, e.g.:

``` r
get_parameters(
  model, 
  effects = c("fixed", "random", "all"),
  component = c("all", "conditional", "zi", "zero_inflated", "dispersion")
)
```

Now the question is where to add the `"location"` option. To `component`?

``` r
get_parameters(
  model, 
  effects = c("fixed", "random", "all"),
  component = c("location", "all", "conditional", "zi", "zero_inflated", "dispersion")
)
```

However, since `"location"` may include fixed and random effects, it also covers the `effects`-argument, though it is an option of the `component`-argument.

**Comment by strengejacke** [comment] 2020-12-17 09:18
> Also, which component would give the brms dpars?

```r
# S3 method for brmsfit
get_parameters(
  x,
  effects = c("fixed", "random", "all"),
  component = c("all", "conditional", "zi", "zero_inflated", "dispersion", "simplex",
    "sigma", "smooth_terms"),
  parameters = NULL,
  summary = FALSE,
  centrality = "mean",
  ...
)
```

**Comment by mattansb** [comment] 2020-12-17 09:25
Yes, `"location"` should go in `component`.

> Also, which component would give the brms dpars?

>
```R
# S3 method for brmsfit
get_parameters(
  x,
  effects = c("fixed", "random", "all"),
  component = c("all", "conditional", "zi", "zero_inflated", "dispersion", "simplex",
    "sigma", "smooth_terms"),
  parameters = NULL,
  summary = FALSE,
  centrality = "mean",
  ...
)
```

Sorry if I'm missing something, but I still can't figure out _which_ of the component options gives the distributional parameters? E.g., if I run this https://github.com/easystats/insight/issues/268#issuecomment-745817954, which will give me the `beta` of the exgaussian?  Is it "sigma"? (If so, we might want to change/alias to "dpar" or something) Or a different one?

**Comment by strengejacke** [comment] 2020-12-17 09:35
```r
get_parameters(x, effects = "fixed", component = "conditional")
```

or the default

```r
get_parameters(x, effects = "all", component = "all")
# which is
get_parameters(x)
```

**Comment by strengejacke** [comment] 2020-12-17 09:42
> E.g., if I run this #268 (comment), which will give me the beta of the exgaussian?

I think this is not implemented yet.

**Comment by strengejacke** [comment] 2020-12-17 09:45
This is what currently will be extracted from brmsfit:

```r
  cond <- fe[grepl(pattern = "^(b_|bs_|bsp_|bcs_)(?!zi_)(.*)", fe, perl = TRUE)]
  zi <- fe[grepl(pattern = "^(b_zi_|bs_zi_|bsp_zi_|bcs_zi_)", fe, perl = TRUE)]
  rand <- fe[grepl(pattern = "(?!.*__zi)(?=.*^r_)", fe, perl = TRUE) & !grepl(pattern = "^prior_", fe, perl = TRUE)]
  randzi <- fe[grepl(pattern = "^r_(.*__zi)", fe, perl = TRUE)]
  simo <- fe[grepl(pattern = "^simo_", fe, perl = TRUE)]
  smooth_terms <- fe[grepl(pattern = "^sds_", fe, perl = TRUE)]
  priors <- fe[grepl(pattern = "^prior_", fe, perl = TRUE)]
  sigma <- fe[grepl(pattern = "^sigma_", fe, perl = TRUE)]
  rand_sd <- fe[grepl(pattern = "(?!.*_zi)(?=.*^sd_)", fe, perl = TRUE)]
  randzi_sd <- fe[grepl(pattern = "^sd_(.*_zi)", fe, perl = TRUE)]
  rand_cor <- fe[grepl(pattern = "(?!.*_zi)(?=.*^cor_)", fe, perl = TRUE)]
  randzi_cor <- fe[grepl(pattern = "^cor_(.*_zi)", fe, perl = TRUE)]

  l <- .compact_list(list(
    conditional = cond,
    random = c(rand, rand_sd, rand_cor),
    zero_inflated = zi,
    zero_inflated_random = c(randzi, randzi_sd, randzi_cor),
    simplex = simo,
    smooth_terms = smooth_terms,
    sigma = sigma,
    priors = priors
  ))
```

**Comment by mattansb** [comment] 2020-12-17 12:18
> I think this is not implemented yet.

Okay, that's what I was missing (:
I think (but not sure) that everything not caught by those 👆 `grepl`s (and is no `lp__`) is a `dpar` parameter.
Do you want me to open a separate issue for that?

**Comment by strengejacke** [comment] 2020-12-17 13:13
No, I think we can cover this topic here. :-)

**Comment by strengejacke** [comment] 2020-12-17 13:50
This issue becomes more and more related to #230 - we should think about a common name ("auxiliary" or "distributional"), to avoid having multiple names for the same thing.

**Comment by mattansb** [comment] 2020-12-17 14:28
- `get_sigma` - since sigma is a special case, it can have it's own function I guess.
- `get_distributional` - returns sigma and any other distributional parameters (as covered here and in #230)
- `get_parameters` - _can_ return all parameters (including those from `get_distributional`) but defaults to give the "location" parameters. 

How does that sound?

**Comment by strengejacke** [comment] 2020-12-22 18:18
Do you have an example for a model with dispersion parameter?

**Comment by strengejacke** [comment] 2020-12-22 18:23
Current implementation:

```r
  # all elements - based on arguments "effects" and "component", one
  # or more of these are returned.
  elements <- c("conditional", "conditional2", "conditional3", "precision",
                "nonlinear", "random", "zero_inflated", "zero_inflated_random",
                "dispersion", "instruments", "interactions", "simplex",
                "smooth_terms", "sigma", "nu", "tau", "correlation", "slopes",
                "cluster", "extra", "scale", "marginal", "beta")

  # auxiliary parameters - if component = "distributional"
  auxiliary_parameters <- c("sigma", "beta", "dispersion", "precision", "nu", "tau")

  # location parameters - if component = "location"
  location_parameters <- setdiff(elements, auxiliary_parameters)
```

**Comment by strengejacke** [comment] 2020-12-22 18:36
takes hours to fit the exgaussian model, @mattansb maybe you can check if it works to retrieve beta now with `get_parameters(model, component = "distributional")`?

**Comment by mattansb** [comment] 2020-12-22 18:55
This took 12 seconds to run... 🙃

```R
library(brms)

d <- data.frame(y = 1:10)

m <- brm(y ~ 1, family = exgaussian(), data = d)

get_parameters(m, component = "distributional")
#> data frame with 0 columns and 4000 rows
```

**Comment by strengejacke** [comment] 2020-12-22 21:26
Hm, ok. Can you attach the compiled brmsfit object here to this issue?

**Comment by DominiqueMakowski** [comment] 2020-12-23 00:37
![image](https://user-images.githubusercontent.com/8875533/102945904-07e6a180-44fa-11eb-9438-615af6607262.png)

**Comment by mattansb** [comment] 2020-12-23 05:03
@strengejacke 
[exgauss.zip](https://github.com/easystats/insight/files/5733375/exgauss.zip)

**Closed** 2021-04-04 20:45 UTC
Labels: enhancement :boom:
