### ISSUE TITLE
Strange error in CRAN checks

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#286] opened 2021-01-16 22:21 UTC
@IndrajeetPatil @mattansb @DominiqueMakowski 

Any idea what this could be?
https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/insight-00check.html

Not sure if it's even testthat related?

**Comment by mattansb** [comment] 2021-01-17 01:57
Weird... Might be something local on CRAN? No idea..

**Comment by IndrajeetPatil** [comment] 2021-01-17 07:04
It might be something temporary. Let's wait for a few more days and see if the error persists. Often these errors disappear on their own.

**Comment by strengejacke** [comment] 2021-02-01 16:41
Here are some more information / insights:
https://github.com/r-lib/testthat/issues/1313#issuecomment-770963204

**Comment by IndrajeetPatil** [comment] 2021-02-03 17:28
When I run tests on my Mac (but **never** on Windows), I actually _do_ run into this error once in a while. And it is rather unpredictable. Happens in `test-gamm4.R` most of the time.

**Comment by vincentarelbundock** [comment] 2021-02-03 17:39
I played with `tinytest` a bit, but only interactively, and I never deployed it in a real-world package. It looks like a *really* neat framework, and I would consider it if I were to start a new package. But like @IndrajeetPatil , I feel like the costs of porting over existing tests would exceed the benefits. 

There's also network effects to consider, since `testthat` is soooo widespread that CRAN and Github actions support is likely better. (Maybe that's unfounded.)

I also wouldn't worry too much about an obscure and inconsistent error produced in one environment, and just skip it. (But maybe I'm not strict enough.)

**Comment by strengejacke** [comment] 2021-02-03 17:51
The error is rather new and the message is quite strange, so I think this might be due to the latest changes to testthat 3rd edition.

**Comment by strengejacke** [comment] 2021-02-03 18:01
> I feel like the costs of porting over existing tests would exceed the benefits.

Since function names are identical, there's probably less work than expected. But yes, I'm not sure how well other test packages integrate into GitHub actions.

**Comment by IndrajeetPatil** [comment] 2021-02-11 09:47
This is definitely a bug in `testthat` that affects only when you run tests in parallel & on MacOS & for regression object related testing.

I don't know how I can prepare a reprex for such a thing though. I'd consider setting `skip_on_os("mac")` for such tests, so that they don't error in CRAN checks.

**Comment by strengejacke** [comment] 2021-02-11 10:58
Hadley said (see https://github.com/easystats/insight/issues/286#issuecomment-770990833), it's unlikely to be testthat related. I'm not sure, hard to figure out. The problem is, based on the error shown on CRAN, you can't even figure out which test is failing. So one way would be to skip tests on that OS / system in general...

**Comment by IndrajeetPatil** [comment] 2021-02-11 11:04
> The problem is, based on the error shown on CRAN, you can't even figure out which test is failing. 

Yeah, that's true.

Gabor pointed out that it's `test-emmGrid.R`? I have also experienced it with `test-gamm4.R`.
So maybe we can start by skipping these two for starters?

Skipping on `MacOS` in general will be a bit too reckless, in my opinion.

**Comment by IndrajeetPatil** [comment] 2021-02-11 19:34
Another option is to just turn of parallel testing. Slower is better, if it means none of the tests will fail. 

Just remove this line:
https://github.com/easystats/insight/blob/a8de6ad46a9419f87916e1b487855cfabe3395e6/DESCRIPTION#L143

**Comment by strengejacke** [comment] 2021-02-11 20:06
Yeah, I though about that, too. The question is, how much is the speed benefit when parallel testing is set to TRUE? Do we lose much time?

**Comment by IndrajeetPatil** [comment] 2021-02-11 20:15
So here is what I see on my local Windows machine with `R-devel`:

- **Without** parallel: `Duration: 136.8 s`
- **With** parallel: `Duration: 99.2 s`

**Comment by IndrajeetPatil** [comment] 2021-02-12 16:16
Closing this for now as https://github.com/easystats/insight/commit/525a397ac1307bd117e77fac5855b7b772974f23 would fix this.

**Closed by IndrajeetPatil** 2021-02-12 16:16 UTC
Labels: 3 investigators :grey_question::question:, question :interrobang:
